
psql_host=$1
port_host=$2
db_name=$3
user_name=$4
password=$5


lscpu_out=`lscpu`

get_hostname(){
	hostname=$(hostname -f)
}

get_cpu_number(){
	cpu_number=$(echo "$lscpu_out" | egrep "^CPU\(s\):" | awk '{print $2}' | xargs)
}

get_lscpu_value(){
	pattern=$1
	value=$(echo "$lscpu_out" | egrep "$pattern" | awk -F':' '{print $2}' | xargs)
	echo "value=$value"
}

get_cpu_architecture(){
	get_lscpu_value "Architecture"
	cpu_architecture=$value
}

get_cpu_model(){
	get_lscpu_value "Model"
	cpu_model=$value
}

get_cpu_mhz(){
	get_lscpu_value "MHZ"
	cpu_mhz=$value
	
}

get_L2_cache(){
	get_lscpu_value "L2_cache"
	L2_cache=$value
}



get_hostname
get_cpu_number
get_cpu_architecture
get_cpu_model
get_cpu_mhz
get_L2_cache
total_mem=$(cat /proc/meminfo|egrep MemTotal | awk '{print $2}')
timestamp=$(date "+%Y-%m-%d %H:%M:%S")

#Step2:construct INSERT statement
insert_stmt=$(cat <<-END
INSERT INTO host_info(hostname,cpu_number,cpu_architecture,cpu_model,cpu_mhz,12_cache,total_mem,"timestamp") VALUES('${hostname}',${cpu_number},'$cpu_architecture}','${cpu_model}',${cpu_mhz},${L2_cache},${total_mem},'${timestamp}');
END
)
echo $insert_stmt

#step3:Excute INSERT statement
export PGPASSWORD=$password
psql -h $psql_host -p $port -U $user_name -d $db_name -c "$insert_stmt"

#step4:Save host_id generated by PSQL table to a local file
psql -h localhost -U postgres host_agent -c "select * from host_info where host_name='${hostname}'" | tail -3 | head -1 | xargs`
echo $host_id > ~/host_id
cat ~/host_id
